build_platform:
  linux_aarch64: linux_64
  osx_arm64: osx_arm64
conda_build:
  pkg_format: '2'
conda_forge_output_validation: true
provider:
  linux: github_actions
  win: github_actions
  osx: github_actions
github:
  branch_name: main
  tooling_branch_name: main
test: native_and_emulated
